### PR TITLE
I won the intro text thing on the discord

### PR DESCRIPTION
**Pull request by GamerZoneYT**
Somebody in the discord said this is how I get it added so... here you go i guess.

"subscribe to--gamerzone"

### CODE REVIEW

**Comment by george2781** [comment]
tf

**Comment by nickpythonluajava** [comment]
i was playing crappy mobile fnf port this better be good

**Comment by george2781** [comment]
ProjectFNF for mobile when

**Comment by nickpythonluajava** [comment]
> ProjectFNF for mobile when

aight im on it

**Comment by george2781** [comment]
> 
> 
> > ProjectFNF for mobile when
> 
> aight im on it

Keep me updated lol

**Comment by george2781** [comment]
I'll wait for this to be merged before my recompile ig

**Comment by MagnusStrom** [comment]
done

**Pull request closed without merging**
