### PR TITLE
app and executable name is now ProjectFNF

### PR DESCRIPTION
**Pull request by actuallyasmartname**

### CODE REVIEW

**Comment by VMGuy23** [comment]
Have you changed the compile settings to use ProjectFNF? Or is that the compile setttings

**Comment by actuallyasmartname** [comment]
> Have you changed the compile settings to use ProjectFNF? Or is that the compile setttings

not sure i'll try to do that if it isn't

**Comment by actuallyasmartname** [comment]
probably is ProjectFNF though

**Comment by VMGuy23** [comment]
I mean, have you changed what the compiled executable is called? Try building your version and check.

**Comment by actuallyasmartname** [comment]
yeah it did change

**Pull request merged**
