### PR TITLE
Add vs H

### PR DESCRIPTION
**Pull request by Funkin-VS-H**
im making it with projectfnf

### CODE REVIEW

**Comment by nickpythonluajava** [comment]
ok

**Comment by VMGuy23** [comment]
h

**Comment by nickpythonluajava** [comment]
h

**Comment by MagnusStrom** [comment]
No? Just Fork it.

**Comment by VMGuy23** [comment]
> No? Just Fork it.

I'm saying to add it to the global list of mods that use ProjectFNF. Neo is already there, vs H is something I'm working on that will be made with ProjectFNF

**Pull request closed without merging**
