### PR TITLE
Add IRC notifications for new commits

### PR DESCRIPTION
**Pull request by VMGuy23**
Should I or you set up IRC channel and bot nick? anyway it's on freenode and a nice fast way to communicate

### CODE REVIEW

**Comment by aflacc** [comment]
absolutely

**Comment by aflacc** [comment]
wait can I pull this yet orrrrrr.........?

**Comment by VMGuy23** [comment]
Should I set up the channel? After that you can pull.

**Comment by aflacc** [comment]
wait is this like a discord thing orrrrrrr

**Comment by VMGuy23** [comment]
IRC. Discord before it existed, without calls and voice chat. Different public channels between plenty of people. Connect [here](https://webchat.freenode.net/)

**Comment by VMGuy23** [comment]
...or use an IR client. That's the webchat.

**Comment by VMGuy23** [comment]
So... should I create it? I have an over-a-month-old registered account on there.

**Comment by aflacc** [comment]
I guess. How come you aren't on discord?

**Comment by VMGuy23** [comment]
idk but will have it by the end of the month. Creating now, you can pull

**Comment by aflacc** [comment]
👍 discords free to use btw theres no reason you need to wait

**Comment by VMGuy23** [comment]
I know. But I like IRC and it's _pretty much instant message times, even on slow connections_

**Comment by VMGuy23** [comment]
ANT IT'S CREATED! All pushes after this pr should send a message

**Comment by aflacc** [comment]
aight neato

**Comment by VMGuy23** [comment]
Try pushing something (adding "H" to the end of readme or something)

**Comment by VMGuy23** [comment]
It worked :)
image
Join #projectfnf in Freenode webchat

**Pull request merged**
