### PR TITLE
Change icon grid to use cool harder funkin icons

### PR DESCRIPTION
**Pull request by VMGuy23**
glimpse image editor

### CODE REVIEW

**Comment by MagnusStrom** [comment]
Cute!

**Comment by VMGuy23** [comment]
> I'm gonna try and revert this

Understandable I thought you made it

**Comment by aflacc** [comment]
> > I'm gonna try and revert this
> 
> Understandable I thought you made it

Nah its fine. I also don't really think that fits as a base thing.

**Comment by aflacc** [comment]
Not to mention I dont think the healthicon file would like that icongrid

**Comment by VMGuy23** [comment]
Why wouldn't it?

**Comment by nickpythonluajava** [comment]
> Why wouldn't it?

the icons have different positions so you would have to change it

**Comment by VMGuy23** [comment]
> > Why wouldn't it?
> 
> the icons have different positions so you would have to change it
> 
> (or im stupid and you edited it in place)

I edited it in place. Made sure

**Pull request merged**
