### PR TITLE
Yet Another Readme Change

### PR DESCRIPTION
**Pull request by actuallyasmartname**
VS part works (https://github.com/ninjamuffin99/Funkin/pull/1040)
Replaces "sudo apt install git" with just "install Git" (thanks @VMGuy23)
(also centers the projectfnf logo and text after it)

### CODE REVIEW

**Comment by VR-Core** [comment]
Cock and ball torture

**Comment by aflacc** [comment]
hm? What do this do tho

**Comment by VMGuy23** [comment]
> Cock and ball torture

Please explain

**Comment by VR-Core** [comment]
> > > Cock and ball torture
> > 
> > 
> > Please explain
> 
> hes just being funny

I’m funny man

**Comment by actuallyasmartname** [comment]
looks like this crap works

**Comment by aflacc** [comment]
YES

**Comment by VMGuy23** [comment]
There's a conflict

**Comment by prokube** [comment]
yaaaarrrrrrrc matey

**Comment by aflacc** [comment]
fix the conflict and ill pull

**Comment by aflacc** [comment]
I wonder if i can just copy the code over

**Comment by VMGuy23** [comment]
Maybe.

**Comment by aflacc** [comment]
yeah i just copied all the code and slapped it in there

**Comment by actuallyasmartname** [comment]
https://github.com/aflacc/ProjectFNF/commit/70177747e5052c5920364713763305e82609851c

**Pull request closed without merging**
